### ISSUE TITLE
The grey ovals that are projected on the map as a background for step numbers are visible when map isn't open.

### ISSUE THREAD

**Issue by HarmlessHarm** [RestedXP/RXPGuides#10]
While leveling, I noticed that there were grey ovals scattered across my screen. It took me a while to figure out these were the ovals that are visible on your map, where they are used as a background for the step numbers.

I will post a screenshot later today.

I am using Leatrix Maps addon, which allows for a non-fullscreen map, so that might cause the issue, although it would be preferable to have this addon work together with such add-ons.

**Comment by ryanjavens** [comment]
Can you post the screenshot and any Lua error messages you're seeing? Also helpful would be to post the version of Leatrix maps you're using so I can try to replicate :). Thanks!

**Comment by Ann0n** [comment]
I have the same issue.

**Comment by ryanjavens** [comment]
Yes please, along with the version you're using of Leatrix Maps so I can try to recreate it on my side :)

**Comment by Ann0n** [comment]
![Screenshot 2021-05-25 at 21 30 52](https://user-images.githubusercontent.com/45134774/119557500-9066b800-bda0-11eb-91a7-a1cb1e555c0c.png)
![Screenshot 2021-05-25 at 21 30 45](https://user-images.githubusercontent.com/45134774/119557525-978dc600-bda0-11eb-937e-a817aa7f2c5b.png)

Leatrix Maps 2.5.10 from curse

**Comment by Ann0n** [comment]
I tinker in maintaining addons, and have BugGrabber and BugSack, but I dont get any uh'oh-s or popups.

**Comment by ryanjavens** [comment]
Awesome :). I'll try to set this up tonight or tomorrow and see if I can isolate the issue. If there's no error, then maybe Leatrix is doing something with the UI that this addon should account for. Thanks!

**Comment by Ann0n** [comment]
I'll disable the L.Maps and see if they magically go away.

**Comment by ryanjavens** [comment]
2 people with 2 of the same addons having (I think) the same issue. Seems like a common culprit to me :). Since I'm new to addon dev, is this common in your experience @Ann0n ? Are there just some instances of incompatible addons that don't play nice together?

**Comment by Ann0n** [comment]
It does not seem to be related to Leatrix Maps. I still have the issue with it disabled and client restart.

**Comment by ryanjavens** [comment]
Ahhh interesting. Any chance you could list out all of your installed addons? Maybe @HarmlessHarm could do the same?

**Comment by Ann0n** [comment]
I would have thought the wrong parent is being setup for the background.

**Comment by ryanjavens** [comment]
My thoughts are could be related to another addon, or maybe there's a bug in the code and in some situations, these dots are not clearing when closing the map.

**Comment by Ann0n** [comment]
They happen only if you view the map, and complete an objective. When the objective is completed, they appear.

**Comment by ryanjavens** [comment]
Can you detail out the steps?:
1. Open map
2. Close map
3. Complete quest
4. Dots appear?

Is that right, or different from above?

**Comment by Ann0n** [comment]
Yes, always happens for me if I don't change the zone after looking at the map and completing the objective.
(but I didn't test changing zones before completing, so it might happen too.)

**Comment by ryanjavens** [comment]
Hmmm... I just tried the steps above and couldn't recreate the issue.

Again, to detail my steps.

1. I had a quest completed and just needed to turn in as my next objective.
2. I walked up to the NPC
3. I opened my map
4. I closed my map after noting where the gray dot was
5. No dot shown on screen
5. I talked to the NPC which triggered the auto quest turn in and completed the objective
6. No dot shown on screen
7. I opened map again
8. The dot noted in step #4 is gone
9. I closed map again
10. No dot shown on screen

What am I doing differently in above to what's causing the dot to stay on your screen after closing the map?

**Comment by Ann0n** [comment]
The version from my download was not the same as on Github.
I re-downloaded it. Now I no longer have that problem but it seems to have problems with missing guide files.

Download a newer version.

**Comment by ryanjavens** [comment]
@HarmlessHarm can you try updating your addon as well and see if it resolves the issue like it did for @Ann0n ? Thanks!

**Comment by HarmlessHarm** [comment]
The newest version doesn't seem to have the issue anymore! :D

**Comment by ryanjavens** [comment]
Awesome! Maybe I should have recommended that as a start :). Glad it's sorted out for ya now though. Do you mind closing this issue?
