### ISSUE TITLE
wowup repository

### ISSUE THREAD

**Issue by Ann0n** [RestedXP/RXPGuides#11]
It would be cool if there was a repository or URL for wowup.

**Comment by ryanjavens** [comment]
It looks like WoW Up just uses other Addon repos to power itself: https://wowup.io/guide/section/options/addons . I'm not sure where the addon developers are at as far as adding this to something like CurseForge. It looks like the steps to do that are to login to CurseForge and then click "Start Project" here: https://www.curseforge.com/wow/addons .

Anyway, maybe someone from the official RestedXP team can weigh-in on their plans for this :).

**Comment by Ann0n** [comment]
it seems there is now a reference on the website to add using URL
