### ISSUE TITLE
localization

### ISSUE THREAD

**Issue by Mabisi** [RestedXP/RXPGuides#15]
Hello author~ Can you add Chinese? This is a good plugin. Works better than Zygor in my opinion

**Comment by Tacticslol** [comment]
It should already work on the Chinese client. Half of the text is still in English however, do you want everything translated to Chinese?

**Comment by Mabisi** [comment]
> It should already work on the Chinese client. Half of the text is still in English however, do you want everything translated to Chinese?

Yes ~ English and my game client does not fit ~
