### ISSUE TITLE
Add support for group quests

### ISSUE THREAD

**Issue by gtker** [RestedXP/RXPGuides#152]
This is both a request for the addon and for the paid guides but I couldn't find an issue tracker for the guides so I'm not sure if this is the correct place for it.

When duoing from 1-60 as for example priest and warrior there are several quests that are difficult to do solo as either class but are easy as a duo that are not recommended in the guide.

Notably [Defeat Nek'rosh](https://www.wowhead.com/classic/quest=474/defeat-nekrosh), [Fallen Sky Lake](https://www.wowhead.com/classic/quest=1035/fallen-sky-lake), and [Khan Hratha](https://www.wowhead.com/classic/quest=1380/khan-hratha#comments) provide decent rewards and are easy to duo while not being recommended in the priest/warrior guides.

The concrete suggestion is to add a `group` guard condition that is only activated while in a group, or possibly through a setting in the options.

Initially support for this could probably be easily achieved in existing guides by guarding difficult quests behind `hunter || group` instead of just `hunter`.

**Comment by SabreValkyrn** [comment]
Zarant added this, 4ed8fa302f44c8ce124dc7c35f9b52335e785746
