### ISSUE TITLE
Only process HSBatching when hearth step is active

### ISSUE THREAD

**Issue by SabreValkyrn** [RestedXP/RXPGuides#154]
> My FPS drops when I use hearthstone. I disabled all addons, and tried with all of them one by one. It is the RestedXP addon that causes the FPS drop when hearthstone is being used (successfully initiating a cast) or clicked on (not initiating the cast due to GCD, it still produces the issue).

https://discord.com/channels/826162743669162034/1019640113963225179/1066637287502397460

**Comment by Zarant** [comment]
Issue was resolved recently, instead of removing the FPS cap, it sets max FPS to 200 (only when batching window is <= 5ms). This feature is not used in any guide that I know of, but it's mostly a QoL feature that could be used by speedrunners using their own routes.
