### ISSUE TITLE
Class Trainer .skipgossip broken

### ISSUE THREAD

**Issue by TimothyAitchison** [RestedXP/RXPGuides#176]
Currently if you have a .skipgossip, it doesn't skip the gossip for any class trainer.
The guilty line seems to be in functions.lua, line 3713:

` if trainerId and (GossipGetNumOptions() >= 3 or name and strupper(name):find(strupper(localizedClass))) then`

should read

` if trainerId and (GossipGetNumOptions() >= 3 and name and strupper(name):find(strupper(localizedClass))) then`

name and strupper(name):find(strupper(localizedClass)) represents "this is my class trainer, i.e. the dialog contains your class name, and the GossipGetNumOptions() >= 3 seems to be a proxy for "contains a dualspec prompt", but it's evaluating to true if either is the case not both ATM.

Also this check should probably only be executed when trying to select the dualspec with a skipgossip (i.e., id > 1), assuming the intent is to block that?

**Comment by TimothyAitchison** [comment]
P.S. I'm just some random, lemme know if this wasn't the right place to put this but I fixed it on my local copy and thought I'd let you know :)

**Comment by Zarant** [comment]
Just issued a fix, you'll be able to override that check by simply supplying the npc ID, e.g.: for npc ID 123 `.skipgossip 123`
