### ISSUE TITLE
Add a license file

### ISSUE THREAD

**Issue by 10leej** [RestedXP/RXPGuides#178]
There is no license available for this repo there for under US law it's All Rights Reserved by default however this is or might not be the case for other nationalities which means this addon could potentially be considered public domain or other form of re-distributable licensing.  

Which I imagine is a violation of the spirit of a project like this.

**Comment by SabreValkyrn** [comment]
https://www.curseforge.com/wow/addons/restedxp-guide

> All Rights Reserved unless otherwise explicitly stated.

Looks like I don't have repo permissions to update the license, https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

**Comment by random415** [comment]
Wouldn't a free and open source license make sense for this?

**Comment by 10leej** [comment]
I imagine they won't go with GNU as that would immediately invalidate the proprietary nature of the "guide" code they sell.

**Comment by SabreValkyrn** [comment]
Fixed by https://github.com/RestedXP/RXPGuides/commit/3b9212eb36f69898147015363fbedba5822deb9a
