### ISSUE TITLE
Add option to reset guide steps/state

### ISSUE THREAD

**Issue by SabreValkyrn** [RestedXP/RXPGuides#184]
I often see questions on discord about unchecking a manually completed state.

Currently one can reset the guide state by switching to another guide then back and have it replay everything.

Not ideal, but the simplest method to this issue is clearing the `RXPCData.steps` hash and reloading the guide

**Comment by Starlynk1** [comment]
If you have the Step List open, you can go back to whatever step you want and tell it to goto that step.
