### ISSUE TITLE
[Bug] Hide all frames doesn't retain after /reload

### ISSUE THREAD

**Issue by Starlynk1** [RestedXP/RXPGuides#197]
Noticed that when you use the Hide all frames in the options, after a reload the main frame shows up again while the other frames stay hidden.

Reproduce
1. Click on the RXP minimap icon to hide frames
2. /reload
3. Main frames shows up while the other frames stay hidden

At this point, to hide the main frame again you need to click on the minimap icon twice. First click to show all the other hidden frames, second click to hide all frames.

**Comment by SabreValkyrn** [comment]
Should be fixed in latest CF Alpha or 4.5.26 when it's released.
