### ISSUE TITLE
Retrieving quest data...

### ISSUE THREAD

**Issue by kimjoergensen** [RestedXP/RXPGuides#20]
I'm on the guide **40-43 Badlands / Lower Dustwallow** and on step 21 it's just reading _Retrieving quest data_.
What can I do to fix this issue? I'm stuck on the guide.

**Comment by Pocokk** [comment]
Exit the game and  delete the cache folder inside your Wow folder and try again.

**Comment by atstoyanov** [comment]
I have the same problem. Deleting the cache is not working. Reloading the UI works but not always.
