### ISSUE TITLE
Select the "Active Targets" with a macro or keybind?

### ISSUE THREAD

**Issue by Curtisbeef** [RestedXP/RXPGuides#201]
Is there a way to select the "Active Targets" with a macro or keybind?

I did some searching around and couldnt find anything. Was curious if there was a way I could set a keybind to attempt to find new targets without clicking the "Active Targerts" overlay.

Thank you.
- Curtis

**Comment by SabreValkyrn** [comment]
There's an account-wide macro called `RXPTargeting` and keybindings for the first 4 friendlies or enemies.

![image](https://github.com/RestedXP/RXPGuides/assets/61754281/6cc3434c-3a10-48f9-ad97-48718948ad4c)

**Comment by Curtisbeef** [comment]
Ah dang. I didnt even think to look there. Gotcha Ty for the quick response
