### ISSUE TITLE
(Classic Era) Speedrun Guide stops after the 1-20 in SoD

### ISSUE THREAD

**Issue by Starlynk1** [RestedXP/RXPGuides#211]
Playing Season of Discovery and the built in speedrun guide works great. After reaching the end of that guide, we are not able to use our paid guides to continue. I've tried turning SoD option off in Guide Routing, but it defaults back if we try to use a paid guide. Please fix this so we can continue following the guides.

**Comment by rodneygauna** [comment]
I'm having the same issues. I completed most of the levels 20-21 (Ashenvale/Stonetalon), but when I logged on to continue, the guide says I completed all steps and chose a different level tier; I see no list of steps or directions given.

**Comment by Zarant** [comment]
Purging all the guides from memory and importing it again should fix this particular issue, if it doesn't, please contact our support team through [https://www.restedxp.com/help-center/](url)
