### ISSUE TITLE
Can't disable estimated time on Flight Master Map

### ISSUE THREAD

**Issue by Sekt0rX** [RestedXP/RXPGuides#215]
I use a different addon to show the Flight Path timer , so I disable the "Show Flight Timers" option in RXP. 
This option disables the Timer on the footers main window but doesn't remove the Estimated Time on the Flight Master Map, so I have duplicates showing from RXP and my other addon.
I assume from this past ticket (https://github.com/RestedXP/RXPGuides/issues/26) this option should be disabling both features.

Thanks.

**Comment by Starlynk1** [comment]
Tested with latest build and this is still showing in the Flight Master map even though it is disabled in Options.

**Comment by SabreValkyrn** [comment]
7348c0daacf13dac08cf881bc0958e657713f9e4 should fix this in latest alpha/v4.5.50
