### ISSUE TITLE
No guides loading on Classic Era servers

### ISSUE THREAD

**Issue by lucas-nelson** [RestedXP/RXPGuides#23]
I think this change broke guide loading on Classic Era servers:
https://github.com/RestedXP/RXPGuides/commit/d985ee0762e5bf46cd62a3dcab259c27a36d62f3#diff-a9d9466b0a994e7eec8b93f85e0166190e977f9b55ba6c63af9c3499d0cacd6cR38 (`RXPGuides-Classic.toc` last line)

I was unable to see any guides at all to choose from playing Era until I reverted that line of the change.

Problem I was seeing:

![image](https://user-images.githubusercontent.com/5751835/178839679-823956e6-f59b-4c5c-8126-40733bd680ec.png)

After revert:

![image](https://user-images.githubusercontent.com/5751835/178839599-60122081-df08-4538-8931-2c86ae130e4e.png)

**Comment by Zarant** [comment]
fixed on v4.1.2
