### ISSUE TITLE
Lua error upon finding a rare

### ISSUE THREAD

**Issue by Pocokk** [RestedXP/RXPGuides#233]
[ADDON_ACTION_FORBIDDEN] AddOn 'RXPGuides' tried to call the protected function 'TargetUnit()'.
[string "@Interface\AddOns\!BugGrabber\BugGrabber.lua"]:480: in function <Interface\AddOns\!BugGrabber\BugGrabber.lua:480>
[string "=[C]"]: ?
[string "@Interface\AddOns\RXPGuides\Targeting.lua"]:414: in function <Interface\AddOns\RXPGuides\Targeting.lua:397>

**Comment by SabreValkyrn** [comment]
Duplicate https://github.com/RestedXP/RXPGuides/issues/189#issuecomment-1694513775
