### ISSUE TITLE
dark storms

### ISSUE THREAD

**Issue by xenoterracide** [RestedXP/RXPGuides#240]
playing in survival, the [Dark Storms](https://wowpedia.fandom.com/wiki/Dark_Storms_(quest)) quest is really hard, even with knowing to polymorph... I think it should be delayed... and get it later, note: when I got it no message to grind. I'm past it now because I asked for help.

I'm not really playing hardcore/speed run, I just wanted a more optimized (do while you're here) game.

**Comment by Thiddi** [comment]
If the guide sent you to do Dark Storms then you have 'Show Group Quests` toggled on under `Guide Routing`.
This quest is indeed hard so in the survival guide only grouped users are routed there.
