### ISSUE TITLE
Add option to disable flight map times

### ISSUE THREAD

**Issue by Kommeh** [RestedXP/RXPGuides#26]
As a user of Leatrix Plus with with their flight time options enabled it would be nice if we had the option to disable the flight times that are now used by Rested XP on the flight maps when clicking the flight masters. As of now they are listed twice with RXP enabled.

**Comment by SabreValkyrn** [comment]
Are you talking about the estimated time on the flight master map or the flight progress timer that goes on the guide window footer bar?

**Comment by Kommeh** [comment]
Both ideally would have an option but the flight master map is the one that doubles up with leatrix plus.

**Comment by SabreValkyrn** [comment]
Reportedly turning off automate flights doesn't always seem to work either

**Comment by SabreValkyrn** [comment]
https://github.com/RestedXP/RXPGuides/commit/d0cdf0150d8868060f0a2541d05e1090421d3303
