### ISSUE TITLE
Error in chat on login

### ISSUE THREAD

**Issue by Larsy93** [RestedXP/RXPGuides#27]
Error parsing guide 64-65 Nagrand: No item ID provided
.destroy 24475 You can delete "Gordawg's Imprint" from your bags, as it's no longer needed

**Comment by Larsy93** [comment]
Still an issue.

**Comment by Calamityrxp** [comment]
It is fixed next update, I promise. We haven't released it yet.

**Comment by Larsy93** [comment]
> It is fixed next update, I promise. We haven't released it yet.

Yay, was confused there for a second 👍
