### ISSUE TITLE
Why does the Horde 20-23 guide have you doing level 17 quests?

### ISSUE THREAD

**Issue by Jakobud** [RestedXP/RXPGuides#34]
There is a part of the 20-23 Horde Guide (Stonetalon/Barrens) where it has you going into the Wailing Caverns cave to do level 17, 18, etc quests like Serpentbloom and Deviate Hides.....

https://github.com/RestedXP/RXPGuides/blob/main/Guides/RestedXP%20Horde%2020-30.lua#L563

Why is this? That doesn't seem very optimal at all. A green level 17 quest for example is going to reward you with a low amount of xp per time spent when you are level 20, 21, 22, 23, etc...

These guides should have you doing yellow quests almost exclusively...

**Comment by Calamityrxp** [comment]
This is removed in 50% exp routing for non shamans/warriors, and was recently fixed for shamans/warriors in a future update.
