### ISSUE TITLE
Question on updated guides

### ISSUE THREAD

**Issue by linkx2252** [RestedXP/RXPGuides#35]
Hi, quick question.

If a guide gets updated, does the guide automatically get updated when a new version of addon comes out? Or do we have to update the guide by reimporting the string from orders page?

**Comment by Calamityrxp** [comment]
You will need to reimport the guide when the guide is updated. Guide and addon updates are seperate. Please use our discord @ discord.gg/restedxp in the future for this type of question, we don't check here as often as we do there.
