### ISSUE TITLE
Horde Hillsbrad / Druid quest order is a bit weird

### ISSUE THREAD

**Issue by Jakobud** [RestedXP/RXPGuides#37]
https://github.com/RestedXP/RXPGuides/blob/main/Guides/RestedXP%20Horde%2020-30.lua#L1317

Here you just finish Battle of Hillsbrad, but it doesn't instruction you to turn it in. If you are a Druid, it instead has you try to complete your Pendant of the Sea Lion, but you can't do that unless you are already in Moonglade and are standing at the Shrine of Remulos.

Then the guide has you port to moonglade

Then hearth to Org. Then it says 

"We're not going to turn these quests in until later on". I have no idea what quests it's talking about.

The order should be:

1. Turn in Battle of Hillsbrad
2. (If druid) Teleport to Moonglade
3. (if druid) Go to Shrine of Remulos in Moonglade
4. (if druid) Combine the pendants
5. (if druid) Turn in the trial of the sea lion
6. Hearth to Orgrimmar

**Comment by SabreValkyrn** [comment]
This may already be optimized, please hit up the guide contributors in Discord, they'll have better support there.

See "Open Feedbackr Form" in game to make it easier.
