### ISSUE TITLE
Feature request: Show/Hide the step list

### ISSUE THREAD

**Issue by einarwar** [RestedXP/RXPGuides#41]
Hello, and thanks for doing an awesome job.

I am using v4.2.7 and have tried to find a way to hide the main addon widget containing the steps and options buttons, but could not find any options for this. It's kind of dramatic to disable the addon in order to be able to hide it. A suggestion of placement of this hide/show button is in the list that is shown when pressing the options button

![image](https://user-images.githubusercontent.com/21360860/186260691-7da15aec-dd49-4d2f-99d3-aacbb54d5c30.png)

**Comment by SabreValkyrn** [comment]
`/rxp hide` and `/rxp show` will be in the next release, to temporarily hide/show that GuideWindow.

There's also a "Hide Window" addon setting you can use.
