### ISSUE TITLE
Waypoint Arrow label text size not saved between sessions

### ISSUE THREAD

**Issue by Nicodareus** [RestedXP/RXPGuides#71]
**Steps to reproduce:** 
![image](https://user-images.githubusercontent.com/114642158/192948967-ab10f9c7-9aff-40cc-893c-365ce96dd867.png)

**1.** Change the font size of the Arrow Text Size in the Interface window. (in the example used i chose 11)
**2.** Click Okay in the Interface window.
**3.** Reload the UI.

**Observed behavior:** 

- The size of the font reverts to the default without visibly changing the slider or the number after reloading UI

![image](https://user-images.githubusercontent.com/114642158/192950008-4070d09f-4afd-4675-861f-8a62c3735d72.png)
![image](https://user-images.githubusercontent.com/114642158/192949863-5f73e3ec-6ebe-4993-8995-1fb4fe183ffc.png)

**Expected behavior:**

- The size of the font for the Arrow Text Size is expected to be saved between sessions

**Unrelated to the bug:**
Hi, new to github, but myself and my friends love your speedrun addon, so i had to make an account to address an issue that is mildly annoying but doesn't ultimately break any functionality of the addon. Thanks for your time! :)

**Comment by SabreValkyrn** [comment]
What version of the addon are you on? Pretty sure I fixed that in `v4.3.3`, can't repro on 4.3.9 either.

**Comment by Nicodareus** [comment]
Oh, strange i was using 4.3.2. I'll get the newest version then. Sorry for wasting your time!
