### ISSUE TITLE
Icecrown Quest Guide has you set hearth to Argent Tournament Grounds but that isn't in the game

### ISSUE THREAD

**Issue by garrettmusto** [RestedXP/RXPGuides#72]
In Wrath Classic, during the Icecrown questing guide, step 52 has you set your hearth to the Silver Covenant Pavilion. Later, step 88 has you hearth to the Argent Tournament Grounds. This happens again in step 185. The Argent Tournament Grounds aren't currently in Wrath Classic and won't be added for a couple of phases.

**Comment by SabreValkyrn** [comment]
Please direct guide feedback to https://discord.gg/restedxp using the in-addon feedback form.

But this is fixed with v10 of guides, released 12 hours ago.
