### ISSUE TITLE
Fix Active Item Frame lua errors

### ISSUE THREAD

**Issue by SabreValkyrn** [RestedXP/RXPGuides#87]
In certain situations, the Active Item Frame doesn't automatically hide or results in a lua error.

**Comment by SabreValkyrn** [comment]
```
1x [ADDON_ACTION_BLOCKED] AddOn 'RXPGuides' tried to call the protected function 'RXPItemFrame:Hide()'.
[string "@Interface\AddOns\!BugGrabber\BugGrabber.lua"]:480: in function <Interface\AddOns\!BugGrabber\BugGrabber.lua:480>
[string "=[C]"]: in function `Hide'
[string "@Interface\AddOns\RXPGuides\RXPGuides-@project-version@.lua"]:632: in function <Interface\AddOns\RXPGuides\RXPGuides.lua:626>
[string "=[C]"]: ?
```

**Comment by HelloMikko** [comment]
Theres another that a friend showed me on his screen that pops up:
`restedxp blocked function: TargetUnit() (RXPGuides)`
you can see the screenshot below:

![Screenshot 2023-01-02 020447](https://user-images.githubusercontent.com/49461213/210202518-6451a2b5-c850-4bd1-827b-dc64cb212e72.png)


The small fix that helps to hide this was too: RXPGuides>Options>Targeting Tab> Uncheck everything(litearlly)>Refresh game. The error goes away.

However, that pretty much just covers up the actual error but when a player needs or wants to use the Targeting system that RXPGuides provides, then... they will not be allowed to do so without having that error as the pic is provided above and will just be in the way plus it keeps returning even after a `/reload` or `/rl`
